<?xml version="1.0" encoding="utf-8"?><Database Name="actualCPProject" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-BEI1D69;Initial Catalog=actualCPProject;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="actualCPProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="CompanyID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PersonInCharge" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Company_Department" Member="Departments" ThisKey="CompanyID" OtherKey="CompanyID" Type="Department" />
    </Type>
  </Table>
  <Table Name="dbo.PartTimer" Member="PartTimers">
    <Type Name="PartTimer">
      <Column Name="ParttimeID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContractPeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Employee_PartTimer" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PersonInCharge" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Employee" />
      <Association Name="Company_Department" Member="Company" ThisKey="CompanyID" OtherKey="CompanyID" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmployeeIC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IfParttimer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_PartTimer" Member="PartTimers" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="PartTimer" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
</Database>